import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "questions.json"
PORTABLE_DATA_PATH = ROOT / "portable" / "questions-data.js"


def question(**kwargs):
    base = {
        "language": "C",
        "common_mistakes": [],
        "related_functions": [],
    }
    base.update(kwargs)
    return base


NEW_QUESTIONS = [
    question(
        id="vos_prique_safe_top",
        title="VosPriQue-先判空再取 Top",
        brief="实现 safe_top：队列为空返回 -1，非空时返回堆顶 int 值。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=2,
        expected_time_seconds=80,
        input_example="pq empty / pq=[7,3]",
        expected_output="-1\n7",
        starter_code="int safe_top(VosPriQue *pq) {\n    /* TODO */\n    return -1;\n}",
        answer_code="int safe_top(VosPriQue *pq) {\n    if (VOS_PriQueEmpty(pq)) return -1;\n    int *top = (int *)VOS_PriQueTop(pq);\n    return top ? *top : -1;\n}",
        explanation="Top 在空队列时没有可用元素，先判空最稳妥；非空时再把返回值转成正确类型指针并解引用。",
        common_mistakes=["对空队列直接 Top 后解引用", "把 Top 返回值当成 int 而不是 int *", "忘记先调用 VOS_PriQueEmpty"],
        related_functions=["VosPriQue"],
        mode="micro",
    ),
    question(
        id="vos_prique_pushbatch_int",
        title="VosPriQue-PushBatch 批量入堆",
        brief="实现 dup_int_item，并配合 VosDupFreeFuncPair + VOS_PriQuePushBatch 批量插入 int 数组。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=3,
        expected_time_seconds=120,
        input_example="arr=[9,1,5]",
        expected_output="size=3 top=9",
        starter_code="void *dup_int_item(void *ptr) {\n    /* TODO */\n    return NULL;\n}",
        answer_code="void *dup_int_item(void *ptr) {\n    int *copy = (int *)malloc(sizeof(int));\n    if (copy == NULL) return NULL;\n    *copy = *(int *)ptr;\n    return copy;\n}",
        explanation="PushBatch 读取连续内存并逐个插入；当元素原始内存生命周期不长于队列时，需要注册 dupFunc 深拷贝每个元素。",
        common_mistakes=["dup 直接返回原指针导致悬挂", "malloc 后忘记拷贝整数值", "PushBatch 时没有传入 pair.dupFunc"],
        related_functions=["VosPriQue"],
        mode="template",
    ),
    question(
        id="vos_prique_clear_reuse",
        title="VosPriQue-Clear 后继续复用",
        brief="先清空优先队列，再重新 push 新元素；Clear 只删成员，不销毁控制块。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=2,
        expected_time_seconds=70,
        input_example="push 7,3 then clear then push 4",
        expected_output="4",
        starter_code="VosPriQue *pq = VOS_PriQueCreate(cmp_max_heap, NULL);\nint a = 7, b = 3, c = 4;\nVOS_PriQuePush(pq, (uintptr_t)&a);\nVOS_PriQuePush(pq, (uintptr_t)&b);\n// TODO: Clear 后再 push c",
        answer_code="VOS_PriQueClear(pq);\nVOS_PriQuePush(pq, (uintptr_t)&c);",
        explanation="Clear 会删除所有成员，但保留队列本身，所以后续还能继续 Push。",
        common_mistakes=["把 Clear 和 Destroy 混淆", "Clear 后继续使用已释放的元素指针", "清空后忘记重新 Push 新元素"],
        related_functions=["VosPriQue"],
        mode="micro",
    ),
    question(
        id="vos_container_of_owner",
        title="VOS_CONTAINER_OF 回到宿主结构",
        brief="已知成员指针 nodePtr，使用 VOS_CONTAINER_OF 取回 Task *。",
        skill_tags=["VOS接口", "宏", "指针"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=2,
        expected_time_seconds=70,
        input_example="Task{id=7,node=123}, nodePtr=&task.node",
        expected_output="7",
        starter_code="typedef struct {\n    int id;\n    int node;\n} Task;\nTask task = {7, 123};\nint *nodePtr = &task.node;\n// TODO: 得到 Task *owner",
        answer_code="Task *owner = VOS_CONTAINER_OF(nodePtr, Task, node);",
        explanation="VOS_CONTAINER_OF 根据成员地址反推整个结构体起始地址，适合链表、树和嵌入式节点场景。",
        common_mistakes=["member 名写错", "把成员指针当成宿主结构地址直接强转", "传错结构体类型"],
        related_functions=["VOS_CONTAINER_OF"],
        mode="micro",
    ),
    question(
        id="vos_prique_cmp_min_int_ptr",
        title="VosPriQue-小顶堆比较函数",
        brief="实现 cmp_min_int_ptr：队列里存 int *，让数值更小的元素排在堆顶。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=3,
        expected_time_seconds=100,
        input_example="push 7,3,5",
        expected_output="top=3",
        starter_code="int32_t cmp_min_int_ptr(uintptr_t data1, uintptr_t data2) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int32_t cmp_min_int_ptr(uintptr_t data1, uintptr_t data2) {\n    const int *a = (const int *)data1;\n    const int *b = (const int *)data2;\n    if (*a == *b) return 0;\n    return *a < *b ? 1 : -1;\n}",
        explanation="VosPriQue 的比较函数返回正数表示 data1 优先。小顶堆要让更小的值优先，所以 *a < *b 时返回正数。",
        common_mistakes=["沿用 data1-data2 写成大顶堆", "忘记 uintptr_t 里存的是 int *", "相等时不返回 0"],
        related_functions=["VosPriQue", "VosPriQueCmpFunc"],
        mode="micro",
    ),
    question(
        id="vos_prique_direct_uintptr_int",
        title="VosPriQue-直接存小整数",
        brief="当整数能放进 uintptr_t 时，直接把值 push 进队列，Top 后再转回 int。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=2,
        expected_time_seconds=80,
        input_example="push 7,3,9 with VOS_IntCmpFunc",
        expected_output="top=9",
        starter_code="VosPriQue *pq = VOS_PriQueCreate(VOS_IntCmpFunc, NULL);\n// TODO: push 7,3,9 并读出 int topValue",
        answer_code="VOS_PriQuePush(pq, (uintptr_t)7);\nVOS_PriQuePush(pq, (uintptr_t)3);\nVOS_PriQuePush(pq, (uintptr_t)9);\nint topValue = (int)VOS_PriQueTop(pq);",
        explanation="头文件说明小整数可以直接存入 uintptr_t，不必申请内存；这种写法下 Top 返回的是数值本身，不要按 int * 解引用。",
        common_mistakes=["把直接存入的整数当成指针解引用", "忘记创建时传 VOS_IntCmpFunc", "把 VOS_PriQueTop 的返回值先转成 void *"],
        related_functions=["VosPriQue", "VOS_IntCmpFunc"],
        mode="micro",
    ),
    question(
        id="vos_prique_pop_all_order",
        title="VosPriQue-连续取堆顶并弹出",
        brief="实现 drain_queue：反复 Top+Pop，把优先队列中的 int * 按优先级写入 out。",
        skill_tags=["VOS接口", "VosPriQue", "优先队列"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=2,
        expected_time_seconds=90,
        input_example="max heap [7,3,9]",
        expected_output="[9,7,3]",
        starter_code="int drain_queue(VosPriQue *pq, int *out) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int drain_queue(VosPriQue *pq, int *out) {\n    int n = 0;\n    while (!VOS_PriQueEmpty(pq)) {\n        int *top = (int *)VOS_PriQueTop(pq);\n        out[n++] = *top;\n        VOS_PriQuePop(pq);\n    }\n    return n;\n}",
        explanation="Top 只读堆顶，不会删除元素；要推进循环必须调用 Pop。循环条件用 VOS_PriQueEmpty，避免空队列取 Top。",
        common_mistakes=["只 Top 不 Pop 导致死循环", "Pop 后再读取旧 top 指针", "空队列时仍调用 Top 并解引用"],
        related_functions=["VosPriQue", "VOS_PriQueTop", "VOS_PriQuePop"],
        mode="micro",
    ),
    question(
        id="vos_prique_dup_free_pair",
        title="VosPriQue-注册 dup/free 钩子",
        brief="创建队列时配置 VosDupFreeFuncPair，让 PushBatch 拷贝元素，并在 Pop/Clear/Destroy 时释放。",
        skill_tags=["VOS接口", "VosPriQue", "内存管理"],
        source_problem="vos_priorityqueue_header_drills",
        difficulty=3,
        expected_time_seconds=110,
        input_example="arr local buffer -> queue owns copies",
        expected_output="pair.dupFunc=dup_int_item pair.freeFunc=free",
        starter_code="void *dup_int_item(void *ptr);\n// TODO: 创建 VosDupFreeFuncPair pair，并用 cmp_min_int_ptr 创建 pq",
        answer_code="VosDupFreeFuncPair pair = {0};\npair.dupFunc = dup_int_item;\npair.freeFunc = free;\nVosPriQue *pq = VOS_PriQueCreate(cmp_min_int_ptr, &pair);",
        explanation="当队列里的元素需要由容器持有副本时，dupFunc 和 freeFunc 要成对注册；否则 PushBatch 后可能引用失效内存或释放不完整。",
        common_mistakes=["只写 dupFunc 不写 freeFunc", "把 pair 的地址漏传给 VOS_PriQueCreate", "把 freeFunc 写成释放局部变量地址"],
        related_functions=["VosPriQue", "VosDupFreeFuncPair"],
        mode="template",
    ),
    question(
        id="uthash_int_count_freq",
        title="uthash-int 计数",
        brief="用 HASH_FIND_INT / HASH_ADD_INT 统计 arr 中每个整数出现次数。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=2,
        expected_time_seconds=90,
        input_example="arr=[4,2,4,3]",
        expected_output="4:2 2:1",
        starter_code="typedef struct IntNode {\n    int key;\n    int cnt;\n    UT_hash_handle hh;\n} IntNode;\nIntNode *map = NULL;\n// TODO: 统计 arr[0..n) 中每个数的出现次数",
        answer_code="for (int i = 0; i < n; ++i) {\n    IntNode *node = NULL;\n    HASH_FIND_INT(map, &arr[i], node);\n    if (node == NULL) {\n        node = (IntNode *)calloc(1, sizeof(IntNode));\n        node->key = arr[i];\n        node->cnt = 1;\n        HASH_ADD_INT(map, key, node);\n    } else {\n        node->cnt += 1;\n    }\n}",
        explanation="uthash 最常见模式是先 FIND，再决定是新增节点还是修改已有节点。",
        common_mistakes=["没找到时直接对 NULL 自增", "新节点忘记给 key 赋值", "ADD 宏字段名写错"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_int_dedup_order",
        title="uthash-int 首次出现去重",
        brief="用 HASH_FIND_INT / HASH_ADD_INT 保留 arr 中每个整数第一次出现的顺序。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=2,
        expected_time_seconds=90,
        input_example="arr=[4,2,4,3,2]",
        expected_output="[4,2,3]",
        starter_code="typedef struct IntNode {\n    int key;\n    UT_hash_handle hh;\n} IntNode;\nIntNode *seen = NULL;\nint out[16] = {0};\nint out_n = 0;\n// TODO: 只保留第一次出现的元素",
        answer_code="for (int i = 0; i < n; ++i) {\n    IntNode *node = NULL;\n    HASH_FIND_INT(seen, &arr[i], node);\n    if (node == NULL) {\n        node = (IntNode *)calloc(1, sizeof(IntNode));\n        node->key = arr[i];\n        HASH_ADD_INT(seen, key, node);\n        out[out_n++] = arr[i];\n    }\n}",
        explanation="uthash 本身不负责保持输入顺序；顺序由你自己的 out 数组控制。",
        common_mistakes=["找到重复元素后仍写入 out", "节点分配后忘记 ADD", "只用 HASH_COUNT 不能去重"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_str_count_freq",
        title="uthash-str 统计词频",
        brief="用 HASH_FIND_STR / HASH_ADD_STR 统计 words 中各单词频次。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=3,
        expected_time_seconds=110,
        input_example="words=[\"err\",\"warn\",\"err\"]",
        expected_output="err:2 warn:1",
        starter_code="typedef struct WordNode {\n    char key[16];\n    int cnt;\n    UT_hash_handle hh;\n} WordNode;\nWordNode *map = NULL;\n// TODO: 统计 words[0..n) 中每个字符串的出现次数",
        answer_code="for (int i = 0; i < n; ++i) {\n    WordNode *node = NULL;\n    HASH_FIND_STR(map, words[i], node);\n    if (node == NULL) {\n        node = (WordNode *)calloc(1, sizeof(WordNode));\n        strcpy_s(node->key, sizeof(node->key), words[i]);\n        node->cnt = 1;\n        HASH_ADD_STR(map, key, node);\n    } else {\n        node->cnt += 1;\n    }\n}",
        explanation="字符串键通常把 key 放进结构体固定数组，再用 HASH_ADD_STR / HASH_FIND_STR。",
        common_mistakes=["把 words[i] 指针直接塞给 key 数组", "忘记复制字符串", "把 HASH_FIND_INT 用在字符串键上"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_delete_int_key",
        title="uthash-删除 int 键",
        brief="构建 int 哈希后删除 key=2，再验证 HASH_COUNT 和是否还能找到 2。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=2,
        expected_time_seconds=80,
        input_example="set={1,2,3}, delete=2",
        expected_output="count=2 has2=0",
        starter_code="typedef struct IntNode {\n    int key;\n    UT_hash_handle hh;\n} IntNode;\nIntNode *set = NULL;\n// TODO: 删除 key=2 对应节点",
        answer_code="IntNode *node = NULL;\nint key = 2;\nHASH_FIND_INT(set, &key, node);\nif (node != NULL) {\n    HASH_DEL(set, node);\n    free(node);\n}",
        explanation="uthash 删除流程是先 FIND 拿到节点，再 HASH_DEL，最后由业务自己 free 节点。",
        common_mistakes=["HASH_DEL 后忘记 free", "没找到时直接删除空指针", "删除后还继续使用旧节点"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_iter_sum_values",
        title="uthash-HASH_ITER 累加值",
        brief="用 HASH_ITER 遍历哈希表，把所有 cnt 累加到 sum。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=2,
        expected_time_seconds=80,
        input_example="map={1:4,2:1,3:3}",
        expected_output="8",
        starter_code="typedef struct IntNode {\n    int key;\n    int cnt;\n    UT_hash_handle hh;\n} IntNode;\nint sum = 0;\n// TODO: 遍历 head 并累加 cnt",
        answer_code="IntNode *cur = NULL;\nIntNode *tmp = NULL;\nHASH_ITER(hh, head, cur, tmp) {\n    sum += cur->cnt;\n}",
        explanation="HASH_ITER 能安全地遍历 uthash 链表结构，也方便后续边遍历边删除。",
        common_mistakes=["直接用 cur=cur->hh.next 时类型不对", "忘记声明 tmp", "把 key 当成 cnt 累加"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_ip_overwrite_mac",
        title="uthash-IP 覆盖旧 MAC",
        brief="若 ip 已存在则覆盖 mac，不存在则新建节点。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=3,
        expected_time_seconds=110,
        input_example="update(123,\"CD-EF-AB-AA-AB-AB\")",
        expected_output="CD-EF-AB-AA-AB-AB",
        starter_code="typedef struct MacNode {\n    int ip;\n    char mac[18];\n    UT_hash_handle hh;\n} MacNode;\nMacNode *table = NULL;\n// TODO: 若 ip=123 已存在则覆盖，否则新增",
        answer_code="MacNode *node = NULL;\nint ip = 123;\nHASH_FIND_INT(table, &ip, node);\nif (node == NULL) {\n    node = (MacNode *)calloc(1, sizeof(MacNode));\n    node->ip = ip;\n    HASH_ADD_INT(table, ip, node);\n}\nstrcpy_s(node->mac, sizeof(node->mac), \"CD-EF-AB-AA-AB-AB\");",
        explanation="ARP 这类题里，uthash 最常见就是按 IP 查找节点，找到覆盖，找不到新建。",
        common_mistakes=["覆盖时忘记先 FIND", "新增节点忘记设置 ip", "mac 缓冲区容量写错"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_count_size",
        title="uthash-HASH_COUNT 取表大小",
        brief="使用 HASH_COUNT 得到当前哈希表节点数，用于容量判断。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=1,
        expected_time_seconds=40,
        input_example="table has 3 nodes",
        expected_output="3",
        starter_code="typedef struct IntNode {\n    int key;\n    UT_hash_handle hh;\n} IntNode;\nIntNode *table = NULL;\n// TODO: 取得当前节点数 count",
        answer_code="unsigned count = HASH_COUNT(table);",
        explanation="uthash 维护了表内节点数量，HASH_COUNT(head) 可以直接读取；ARP 表容量、缓存容量这类题很常用。",
        common_mistakes=["自己遍历计数但漏掉空表", "把 HASH_COUNT 传入节点而不是 head", "用 int 接收也可行但要注意宏返回 unsigned"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_delete_all_iter",
        title="uthash-HASH_ITER 清空整表",
        brief="用 HASH_ITER 安全遍历并删除所有节点，释放内存。",
        skill_tags=["C接口", "uthash", "内存管理"],
        source_problem="uthash_drills",
        difficulty=2,
        expected_time_seconds=90,
        input_example="map={1,2,3}",
        expected_output="count=0",
        starter_code="typedef struct IntNode {\n    int key;\n    UT_hash_handle hh;\n} IntNode;\nIntNode *map = NULL;\n// TODO: 删除并释放 map 中所有节点",
        answer_code="IntNode *cur = NULL;\nIntNode *tmp = NULL;\nHASH_ITER(hh, map, cur, tmp) {\n    HASH_DEL(map, cur);\n    free(cur);\n}",
        explanation="边遍历边删除时必须使用 HASH_ITER 的 tmp 参数保存下一个节点；HASH_DEL 只摘链，不会替你 free。",
        common_mistakes=["普通 for 遍历时删除导致 next 丢失", "HASH_DEL 后忘记 free", "free 后继续访问 cur->hh.next"],
        related_functions=["uthash"],
        mode="micro",
    ),
    question(
        id="uthash_composite_pair_key",
        title="uthash-复合键查找边",
        brief="用结构体 PairKey 作为复合键，按 src,dst 查找或新增一条边。",
        skill_tags=["C接口", "uthash", "哈希"],
        source_problem="uthash_drills",
        difficulty=4,
        expected_time_seconds=150,
        input_example="edge (1,3)=7",
        expected_output="weight=7",
        starter_code="typedef struct {\n    int src;\n    int dst;\n} PairKey;\ntypedef struct EdgeNode {\n    PairKey key;\n    int weight;\n    UT_hash_handle hh;\n} EdgeNode;\nEdgeNode *edges = NULL;\nint src = 1, dst = 3, w = 7;\n// TODO: 按 (src,dst) upsert weight",
        answer_code="PairKey key = {0};\nkey.src = src;\nkey.dst = dst;\nEdgeNode *node = NULL;\nHASH_FIND(hh, edges, &key, sizeof(key), node);\nif (node == NULL) {\n    node = (EdgeNode *)calloc(1, sizeof(EdgeNode));\n    node->key = key;\n    HASH_ADD(hh, edges, key, sizeof(node->key), node);\n}\nnode->weight = w;",
        explanation="多字段键不要拼字符串。把键字段放在结构体里，用 HASH_FIND/HASH_ADD 指定键地址和键长度；复合键先清零可避免结构体 padding 影响匹配。",
        common_mistakes=["用 HASH_FIND_INT 只能比较 src", "新增节点后忘记拷贝整个 key", "HASH_ADD 的 keylen 写成 sizeof(node)", "复合键结构体未清零导致 padding 字节不稳定"],
        related_functions=["uthash"],
        mode="template",
    ),
    question(
        id="uthash_sort_cnt_desc",
        title="uthash-HASH_SORT 按计数降序",
        brief="实现比较函数并调用 HASH_SORT，让 cnt 大的节点排在前面。",
        skill_tags=["C接口", "uthash", "排序"],
        source_problem="uthash_drills",
        difficulty=3,
        expected_time_seconds=110,
        input_example="{4:2, 2:5, 9:1}",
        expected_output="2:5 first",
        starter_code="typedef struct IntNode {\n    int key;\n    int cnt;\n    UT_hash_handle hh;\n} IntNode;\nint cmp_cnt_desc(IntNode *a, IntNode *b) {\n    /* TODO */\n    return 0;\n}\n// TODO: 对 map 调用 HASH_SORT",
        answer_code="int cmp_cnt_desc(IntNode *a, IntNode *b) {\n    if (a->cnt == b->cnt) return a->key - b->key;\n    return b->cnt - a->cnt;\n}\nHASH_SORT(map, cmp_cnt_desc);",
        explanation="HASH_SORT 会重排 uthash 的遍历链表；比较函数小于 0 表示 a 排在 b 前。计数降序时应返回 b->cnt - a->cnt。",
        common_mistakes=["比较方向写反变成升序", "以为 HASH_SORT 会改变哈希查找结果", "计数相同不处理 tie 导致输出不稳定"],
        related_functions=["uthash"],
        mode="template",
    ),
    question(
        id="uthash_per_ip_pkt_cache",
        title="uthash-按 IP 维护报文缓存",
        brief="按 ip 查找缓存桶；不存在则新建，再把 pktId 按升序插入该桶。",
        skill_tags=["C接口", "uthash", "缓存"],
        source_problem="uthash_drills",
        difficulty=4,
        expected_time_seconds=160,
        input_example="ip=456 pktId=8, old=[0,23]",
        expected_output="[0,8,23]",
        starter_code="typedef struct CacheNode {\n    int ip;\n    int pktIds[100];\n    int cnt;\n    UT_hash_handle hh;\n} CacheNode;\nCacheNode *cache = NULL;\nint ip = 456;\nint pktId = 8;\n// TODO: 找到/创建该 IP 缓存桶，并升序插入 pktId",
        answer_code="CacheNode *node = NULL;\nHASH_FIND_INT(cache, &ip, node);\nif (node == NULL) {\n    node = (CacheNode *)calloc(1, sizeof(CacheNode));\n    node->ip = ip;\n    HASH_ADD_INT(cache, ip, node);\n}\nint pos = node->cnt;\nwhile (pos > 0 && node->pktIds[pos - 1] > pktId) {\n    node->pktIds[pos] = node->pktIds[pos - 1];\n    --pos;\n}\nnode->pktIds[pos] = pktId;\nnode->cnt += 1;",
        explanation="ARP miss 缓存可以用 uthash 按 IP 找到桶，桶内用小数组维护 pktId 升序；这样 update 时直接顺序拷贝即可。",
        common_mistakes=["每个报文都建一个哈希节点导致同 IP 难以限额", "只追加 pktId 导致补发顺序错", "新建桶后忘记 HASH_ADD_INT"],
        related_functions=["uthash"],
        mode="template",
    ),
    question(
        id="exam_calc_stack_idx",
        title="模拟计算器-栈名转下标",
        brief="把栈名 a~t 转成 0~19 下标。",
        skill_tags=["长题拆解", "栈", "模拟"],
        source_problem="exam_stack_calculator",
        difficulty=1,
        expected_time_seconds=40,
        input_example="a / t",
        expected_output="0\n19",
        starter_code="int stack_idx(char name) {\n    /* TODO */\n    return -1;\n}",
        answer_code="int stack_idx(char name) {\n    return name - 'a';\n}",
        explanation="题目固定只有 a~t 20 个栈，最简单的映射就是字符减 'a'。",
        common_mistakes=["把 'a' 映射成 1", "忘记字符减法是整数结果"],
        related_functions=[],
        mode="decompose",
        step_order=1,
    ),
    question(
        id="exam_calc_parse_psh",
        title="模拟计算器-解析 PSH 指令",
        brief="用 sscanf_s 解析 \"PSH a 8\"，提取栈名和值。",
        skill_tags=["长题拆解", "解析", "sscanf_s"],
        source_problem="exam_stack_calculator",
        difficulty=2,
        expected_time_seconds=70,
        input_example="PSH a 8",
        expected_output="ok=1 name=a value=8",
        starter_code="int parse_psh(const char *line, char *name, int *value) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int parse_psh(const char *line, char *name, int *value) {\n    char op[8] = {0};\n    if (sscanf_s(line, \"%7s %c %d\", op, (unsigned)sizeof(op), name, value) == 3 && strcmp(op, \"PSH\") == 0) {\n        return 1;\n    }\n    return 0;\n}",
        explanation="PSH 是三段格式：操作名、栈名、整数值。解析后还要校验 op 确实是 PSH。",
        common_mistakes=["只解析 name/value，不校验操作名", "sscanf_s 读字符串时漏传容量", "把 name 写成 int *"],
        related_functions=["sscanf_s"],
        mode="decompose",
        step_order=2,
    ),
    question(
        id="exam_calc_push_if_room",
        title="模拟计算器-满栈时拒绝压栈",
        brief="实现 push_if_room：每个栈容量 32，满栈则返回 0，不做任何修改。",
        skill_tags=["长题拆解", "栈", "模拟"],
        source_problem="exam_stack_calculator",
        difficulty=2,
        expected_time_seconds=80,
        input_example="top=31 push 8 / top=32 push 9",
        expected_output="1 32\n0 32",
        starter_code="int push_if_room(int stacks[][32], int top[], int idx, int value) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int push_if_room(int stacks[][32], int top[], int idx, int value) {\n    if (top[idx] >= 32) return 0;\n    stacks[idx][top[idx]++] = value;\n    return 1;\n}",
        explanation="top[idx] 用作当前元素个数时，写入位置就是 top[idx]，写入后再自增。",
        common_mistakes=["top==31 时误判为满", "先自增再写入导致越位", "满栈时仍修改 top 或栈内容"],
        related_functions=[],
        mode="decompose",
        step_order=3,
    ),
    question(
        id="exam_calc_norm_1024",
        title="模拟计算器-结果按 1024 取模",
        brief="实现 norm1024：当运算结果 >=1024 时，对 1024 取模。",
        skill_tags=["长题拆解", "模拟", "取模"],
        source_problem="exam_stack_calculator",
        difficulty=1,
        expected_time_seconds=40,
        input_example="11 / 1025",
        expected_output="11\n1",
        starter_code="int norm1024(int value) {\n    /* TODO */\n    return value;\n}",
        answer_code="int norm1024(int value) {\n    return value >= 1024 ? value % 1024 : value;\n}",
        explanation="题目只要求结果达到 1024 及以上时再取模，低于 1024 直接保留原值。",
        common_mistakes=["无条件取模虽然大多也对，但没体现题意", "忘记 1024 本身也要取模成 0"],
        related_functions=[],
        mode="decompose",
        step_order=4,
    ),
    question(
        id="exam_calc_div_pair",
        title="模拟计算器-DIV 同时更新商和余数",
        brief="实现 apply_div：lhs 变为商，rhs 变为余数。",
        skill_tags=["长题拆解", "栈", "模拟"],
        source_problem="exam_stack_calculator",
        difficulty=2,
        expected_time_seconds=70,
        input_example="lhs=11 rhs=3",
        expected_output="3,2",
        starter_code="void apply_div(int *lhs, int *rhs) {\n    /* TODO */\n}",
        answer_code="void apply_div(int *lhs, int *rhs) {\n    int a = *lhs;\n    int b = *rhs;\n    *lhs = a / b;\n    *rhs = a % b;\n}",
        explanation="先保存原始 lhs/rhs，再回写商和余数，避免先改 lhs 后丢失被除数。",
        common_mistakes=["先改写 lhs 后再算余数", "把余数写回 lhs", "用更新后的 lhs 再参与求余"],
        related_functions=[],
        mode="decompose",
        step_order=5,
    ),
    question(
        id="exam_calc_collect_tops",
        title="模拟计算器-收集 20 个栈顶值",
        brief="实现 collect_tops：空栈写 -1，非空写各自栈顶。",
        skill_tags=["长题拆解", "栈", "数组"],
        source_problem="exam_stack_calculator",
        difficulty=2,
        expected_time_seconds=70,
        input_example="a top=3, d top=6, 其余空",
        expected_output="3,-1,-1,6",
        starter_code="void collect_tops(int stacks[][32], int top[], int *out) {\n    /* TODO */\n}",
        answer_code="void collect_tops(int stacks[][32], int top[], int *out) {\n    for (int i = 0; i < 20; ++i) {\n        out[i] = top[i] == 0 ? -1 : stacks[i][top[i] - 1];\n    }\n}",
        explanation="top[i] 表示当前元素个数，栈顶位置是 top[i]-1；空栈需要特殊写成 -1。",
        common_mistakes=["空栈时访问 stacks[i][-1]", "把 top[i] 当成最后一个下标", "只收集非空栈，忘记补齐 20 个结果"],
        related_functions=[],
        mode="decompose",
        step_order=6,
    ),
    question(
        id="exam_arp_hash_find_ip",
        title="ARP miss-按 IP 查表",
        brief="用 HASH_FIND_INT 在 ARP 表中按 ip 查找表项。",
        skill_tags=["长题拆解", "uthash", "缓存"],
        source_problem="exam_arp_miss_cache",
        difficulty=2,
        expected_time_seconds=70,
        input_example="table={123->AB}, find 123 / 456",
        expected_output="found\nmissing",
        starter_code="typedef struct ArpNode {\n    int ip;\n    char mac[18];\n    int lastHit;\n    UT_hash_handle hh;\n} ArpNode;\nArpNode *find_entry(ArpNode *table, int ip) {\n    /* TODO */\n    return NULL;\n}",
        answer_code="ArpNode *find_entry(ArpNode *table, int ip) {\n    ArpNode *node = NULL;\n    HASH_FIND_INT(table, &ip, node);\n    return node;\n}",
        explanation="ARP 表按 IP 精确匹配，uthash 的 int 键查找正好对应这个场景。",
        common_mistakes=["把 HASH_FIND_STR 用在 int 键上", "传 ip 而不是 &ip", "找到后忘记返回节点"],
        related_functions=["uthash"],
        mode="decompose",
        step_order=1,
    ),
    question(
        id="exam_arp_choose_lru",
        title="ARP miss-选择最久未命中表项",
        brief="ARP 表满时，选择 lastHit 最小的已用位置作为淘汰目标。",
        skill_tags=["长题拆解", "LRU", "缓存"],
        source_problem="exam_arp_miss_cache",
        difficulty=2,
        expected_time_seconds=70,
        input_example="used=[1,0,1], lastHit=[10,0,3]",
        expected_output="2",
        starter_code="int choose_lru(const int *used, const int *lastHit, int n) {\n    /* TODO */\n    return -1;\n}",
        answer_code="int choose_lru(const int *used, const int *lastHit, int n) {\n    int ans = -1;\n    for (int i = 0; i < n; ++i) {\n        if (!used[i]) continue;\n        if (ans == -1 || lastHit[i] < lastHit[ans]) ans = i;\n    }\n    return ans;\n}",
        explanation="题目要求淘汰最久未被命中的表项，本质就是在已使用位置里找 lastHit 最小值。",
        common_mistakes=["把 lastHit 最大当成最老", "把未使用位置也拿去比较", "初始 ans 没处理导致越界"],
        related_functions=[],
        mode="decompose",
        step_order=2,
    ),
    question(
        id="exam_arp_can_cache_pkt",
        title="ARP miss-总缓存和单 IP 缓存双限制",
        brief="实现 can_cache_pkt：同时满足总缓存上限和单 IP 上限时才返回 1。",
        skill_tags=["长题拆解", "缓存", "边界"],
        source_problem="exam_arp_miss_cache",
        difficulty=1,
        expected_time_seconds=50,
        input_example="(2,3,1,2) / (3,3,1,2) / (2,3,2,2)",
        expected_output="1\n0\n0",
        starter_code="int can_cache_pkt(int totalCached, int cachedPktCap, int perIpCount, int perIpCap) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int can_cache_pkt(int totalCached, int cachedPktCap, int perIpCount, int perIpCap) {\n    return totalCached < cachedPktCap && perIpCount < perIpCap;\n}",
        explanation="两个上限是并列条件，只要任意一个达到上限就不能再缓存。",
        common_mistakes=["只检查总上限", "把 <= 写成 < 反向放过满容量情况", "把两个条件写成或"],
        related_functions=[],
        mode="decompose",
        step_order=3,
    ),
    question(
        id="exam_arp_insert_pkt_sorted",
        title="ARP miss-按 pktId 升序插入缓存",
        brief="实现 insert_pkt_sorted：保持同一 IP 的 pktId 数组始终升序。",
        skill_tags=["长题拆解", "缓存", "数组"],
        source_problem="exam_arp_miss_cache",
        difficulty=2,
        expected_time_seconds=80,
        input_example="pktIds=[0,23], insert 8",
        expected_output="[0,8,23]",
        starter_code="void insert_pkt_sorted(int *pktIds, int *n, int pktId) {\n    /* TODO */\n}",
        answer_code="void insert_pkt_sorted(int *pktIds, int *n, int pktId) {\n    int i = *n;\n    while (i > 0 && pktIds[i - 1] > pktId) {\n        pktIds[i] = pktIds[i - 1];\n        --i;\n    }\n    pktIds[i] = pktId;\n    *n += 1;\n}",
        explanation="补发时要求按 pktId 升序输出，插入时就保持有序能让 update 直接线性返回。",
        common_mistakes=["只追加到末尾导致乱序", "右移元素时覆盖顺序错", "插入后忘记 n 自增"],
        related_functions=[],
        mode="decompose",
        step_order=4,
    ),
    question(
        id="exam_arp_flush_pkt_ids",
        title="ARP miss-补发并清空缓存列表",
        brief="实现 flush_pkt_ids：把当前 pktIds 复制到 out，返回数量，并把列表清空。",
        skill_tags=["长题拆解", "缓存", "数组"],
        source_problem="exam_arp_miss_cache",
        difficulty=2,
        expected_time_seconds=80,
        input_example="pktIds=[0,8,23]",
        expected_output="k=3 out=[0,8,23] remain=0",
        starter_code="int flush_pkt_ids(int *pktIds, int *n, int *out) {\n    /* TODO */\n    return 0;\n}",
        answer_code="int flush_pkt_ids(int *pktIds, int *n, int *out) {\n    int k = *n;\n    for (int i = 0; i < k; ++i) out[i] = pktIds[i];\n    *n = 0;\n    return k;\n}",
        explanation="补发后该 IP 的缓存应立即清空，否则同一批报文会被重复补发。",
        common_mistakes=["复制后忘记把 n 清零", "返回 0 而不是原始数量", "只复制第一个 pktId"],
        related_functions=[],
        mode="decompose",
        step_order=5,
    ),
    question(
        id="exam_arp_upsert_mac",
        title="ARP miss-覆盖旧 MAC 或新增表项",
        brief="若 ip 已存在则覆盖 mac，不存在则新建节点。",
        skill_tags=["长题拆解", "uthash", "缓存"],
        source_problem="exam_arp_miss_cache",
        difficulty=3,
        expected_time_seconds=100,
        input_example="update(123,\"CD-EF-AB-AA-AB-AB\")",
        expected_output="CD-EF-AB-AA-AB-AB",
        starter_code="typedef struct ArpNode {\n    int ip;\n    char mac[18];\n    int lastHit;\n    UT_hash_handle hh;\n} ArpNode;\nArpNode *table = NULL;\n// TODO: ip=123 存在则覆盖，不存在则新增",
        answer_code="ArpNode *node = NULL;\nint ip = 123;\nHASH_FIND_INT(table, &ip, node);\nif (node == NULL) {\n    node = (ArpNode *)calloc(1, sizeof(ArpNode));\n    node->ip = ip;\n    HASH_ADD_INT(table, ip, node);\n}\nstrcpy_s(node->mac, sizeof(node->mac), \"CD-EF-AB-AA-AB-AB\");",
        explanation="update 的核心分支就是 upsert：先按 IP 查找，存在覆盖，不存在新增。",
        common_mistakes=["覆盖时重新建节点导致重复键", "新增节点忘记设置 ip", "mac 缓冲区容量不足"],
        related_functions=["uthash"],
        mode="decompose",
        step_order=6,
    ),
]


def main() -> None:
    questions = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    by_id = {item["id"]: item for item in questions}
    for item in NEW_QUESTIONS:
        by_id[item["id"]] = item
    merged = list(by_id.values())
    merged.sort(key=lambda item: item["id"])
    text = json.dumps(merged, ensure_ascii=False, indent=2) + "\n"
    DATA_PATH.write_text(text, encoding="utf-8")
    PORTABLE_DATA_PATH.write_text("window.QUESTIONS = " + json.dumps(merged, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    print(f"upserted {len(NEW_QUESTIONS)} questions; total={len(merged)}")


if __name__ == "__main__":
    main()
