import json
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "questions.json"
PORTABLE_DATA_PATH = ROOT / "portable" / "questions-data.js"
DOC_PATH = ROOT / "docs" / "timu-micro-breakdown.md"


COMMON = {
    "language": "C",
    "mode": "micro",
    "step_order": None,
}


def drill(
    qid,
    title,
    brief,
    source,
    tags,
    starter,
    answer,
    explanation,
    mistakes,
    funcs,
    difficulty=2,
    seconds=90,
    input_example="见题干",
    expected_output="见题干",
):
    return {
        "id": qid,
        "title": title,
        "brief": brief,
        "skill_tags": tags,
        "source_problem": source,
        "difficulty": difficulty,
        "expected_time_seconds": seconds,
        "input_example": input_example,
        "expected_output": expected_output,
        "starter_code": starter,
        "answer_code": answer,
        "explanation": explanation,
        "common_mistakes": mistakes,
        "related_functions": funcs,
        **COMMON,
    }


DRILLS = [
    drill(
        "classic_vlan_detect_undo",
        "VLAN-识别 undo 命令",
        "判断命令是否以 undo 开头，用于决定本次是允许还是取消 VLAN。",
        "classic_vlan_config",
        ["字符串处理", "C接口", "VLAN拆解"],
        "int is_undo_cmd(const char *cmd) {\n    return 0;\n}",
        "int is_undo_cmd(const char *cmd) {\n    return strncmp(cmd, \"undo \", 5) == 0;\n}",
        "undo 命令有固定前缀，直接比较前 5 个字符即可。",
        ["用 strstr 判断会误判中间包含 undo 的字符串", "忘记空格导致 undoport 也被识别"],
        ["strncmp"],
        input_example='"undo port trunk allow-pass vlan 10"',
        expected_output="1",
    ),
    drill(
        "classic_vlan_expand_to_range",
        "VLAN-识别 to 区间",
        "把 token 序列中的 `20 to 22` 展开成闭区间 [20,22]。",
        "classic_vlan_config",
        ["字符串处理", "区间", "VLAN拆解"],
        "void mark_range(int *allow, int l, int r, int enable) {\n    /* TODO */\n}",
        "void mark_range(int *allow, int l, int r, int enable) {\n    for (int v = l; v <= r; ++v) {\n        allow[v] = enable;\n    }\n}",
        "题目中的 to 是左闭右闭区间，应用命令时直接逐个标记即可，VLAN 最大 4095。",
        ["把右端点写成 < r", "没有处理 undo 的 enable=0", "数组开小导致 4095 越界"],
        ["strtol"],
        input_example="20 to 22, enable=1",
        expected_output="allow[20..22]=1",
    ),
    drill(
        "classic_vlan_skip_fixed_prefix",
        "VLAN-跳过固定命令前缀",
        "从命令中定位 `vlan` 后面的 VLAN 列表起始位置。",
        "classic_vlan_config",
        ["字符串处理", "C接口", "解析"],
        "const char *find_vlan_list(const char *cmd) {\n    return NULL;\n}",
        "const char *find_vlan_list(const char *cmd) {\n    const char *p = strstr(cmd, \" vlan \");\n    return p == NULL ? NULL : p + 6;\n}",
        "固定业务前缀不需要逐词解析，定位 ` vlan ` 后就能进入数字/区间解析。",
        ["返回位置仍指向 vlan 单词", "用固定下标导致 undo 和非 undo 长度不同", "没有处理 NULL"],
        ["strstr"],
        input_example='"port trunk allow-pass vlan 10 20 to 30"',
        expected_output='"10 20 to 30"',
    ),
    drill(
        "classic_vlan_format_min_ranges",
        "VLAN-连续 ID 格式化为最简区间",
        "给定 allow[1..4095]，把连续允许的 VLAN 输出为 `l to r`，单点输出 `l`。",
        "classic_vlan_config",
        ["区间合并", "字符串处理", "格式化"],
        "void append_range(char *out, size_t cap, int l, int r) {\n    /* TODO */\n}",
        "void append_range(char *out, size_t cap, int l, int r) {\n    char buf[32];\n    if (l == r) {\n        sprintf_s(buf, sizeof(buf), \"%d\", l);\n    } else {\n        sprintf_s(buf, sizeof(buf), \"%d to %d\", l, r);\n    }\n    if (out[0] != '\\0') strcat_s(out, cap, \" \");\n    strcat_s(out, cap, buf);\n}",
        "输出时扫描连续段，单点和区间分别格式化，段之间只加一个空格。",
        ["末尾多空格", "把长度为 2 的区间拆成两个单点", "忘记 cap 保护"],
        ["sprintf_s", "strcat_s"],
        difficulty=3,
        seconds=120,
        input_example="allow: 9,21,22,24..30",
        expected_output='"9 21 to 22 24 to 30"',
    ),
    drill(
        "classic_log_forward_match",
        "日志预测-从起点向右匹配 traits",
        "从 events[start] 开始，按子序列规则找到 traits 全部匹配时的最早 end。",
        "classic_log_trait",
        ["双指针", "子序列", "数组"],
        "int find_end(const int *events, int n, const int *traits, int m, int start) {\n    return -1;\n}",
        "int find_end(const int *events, int n, const int *traits, int m, int start) {\n    int j = 0;\n    for (int i = start; i < n; ++i) {\n        if (events[i] == traits[j] && ++j == m) return i;\n    }\n    return -1;\n}",
        "匹配规则是子序列，不要求连续；events 指针向右扫，traits 指针只在命中时移动。",
        ["把匹配理解成连续相等", "traits 下标越界", "匹配到最后一个后没有立即返回"],
        [],
        input_example="events=[4,8,4,3,6,6,8], traits=[4,6,8], start=0",
        expected_output="6",
    ),
    drill(
        "classic_log_backward_shrink",
        "日志预测-从 end 反向收缩最短窗口",
        "已知 end 能匹配完整 traits，从 end 向左反推最靠右的 start。",
        "classic_log_trait",
        ["双指针", "滑窗", "子序列"],
        "int shrink_start(const int *events, const int *traits, int m, int end) {\n    return -1;\n}",
        "int shrink_start(const int *events, const int *traits, int m, int end) {\n    int j = m - 1;\n    for (int i = end; i >= 0; --i) {\n        if (events[i] == traits[j] && --j < 0) return i;\n    }\n    return -1;\n}",
        "正向找到一个可行 end 后，反向匹配 traits 可得到该 end 下的最短 start。",
        ["反向仍从 traits[0] 开始", "返回了第一个匹配位置而非完整匹配后的 start"],
        [],
        difficulty=3,
        input_example="end=6",
        expected_output="2",
    ),
    drill(
        "classic_log_update_best_window",
        "日志预测-最短窗口与最早窗口更新",
        "遍历所有可行窗口，长度更短才更新；长度相同保留更早出现的窗口。",
        "classic_log_trait",
        ["滑窗", "边界条件"],
        "void update_best(int l, int r, int *bestL, int *bestR) {\n    /* TODO */\n}",
        "void update_best(int l, int r, int *bestL, int *bestR) {\n    if (*bestL < 0 || r - l < *bestR - *bestL) {\n        *bestL = l;\n        *bestR = r;\n    }\n}",
        "题目要求多个最短时返回最早匹配到的窗口，因此相同长度不要覆盖旧答案。",
        ["长度相同时覆盖导致返回更晚窗口", "用 <= 更新", "比较长度时忘记闭区间一致性"],
        [],
        input_example="old=[2,6], new=[0,4]",
        expected_output="保留 old",
    ),
    drill(
        "classic_line_normalize_edge",
        "专线配置-规范化双向边",
        "把 (id1,id2) 规范成 id1 < id2，便于查找和比较。",
        "classic_private_line",
        ["图", "哈希", "规范化"],
        "void normalize_pair(int *a, int *b) {\n    /* TODO */\n}",
        "void normalize_pair(int *a, int *b) {\n    if (*a > *b) {\n        int t = *a; *a = *b; *b = t;\n    }\n}",
        "专线是双向的，统一端点顺序后才能避免 [2,3] 和 [3,2] 被当成两条线。",
        ["忘记交换导致删除失败", "只在新增时规范化，删除时没规范化"],
        [],
    ),
    drill(
        "classic_line_occupy_ports",
        "专线配置-新增时检查端口占用",
        "只有两个端口都未被占用时，才能新增专线并标记占用。",
        "classic_private_line",
        ["数组", "状态模拟"],
        "int try_add(int used[], int a, int b) {\n    return 0;\n}",
        "int try_add(int used[], int a, int b) {\n    if (used[a] || used[b]) return 0;\n    used[a] = used[b] = 1;\n    return 1;\n}",
        "新增成功条件是两个端口都空闲；失败时不能修改任何状态。",
        ["只检查一个端口", "失败时仍然占用了另一个端口", "删除后忘记释放端口"],
        [],
        input_example="used[5]=1, add(5,6)",
        expected_output="0",
    ),
    drill(
        "classic_line_diff_initial_current",
        "专线配置-比较初始与最终配置",
        "用初始集合和最终集合生成删除/新增命令：初始有最终无则删，最终有初始无则增。",
        "classic_private_line",
        ["集合差集", "排序"],
        "/* init[a][b], cur[a][b] 已有 */\n/* TODO: 生成 del/add */",
        "for (int a = 0; a <= 100; ++a) {\n    for (int b = a + 1; b <= 100; ++b) {\n        if (init[a][b] && !cur[a][b]) add_cmd('d', a, b);\n    }\n}\nfor (int a = 0; a <= 100; ++a) {\n    for (int b = a + 1; b <= 100; ++b) {\n        if (!init[a][b] && cur[a][b]) add_cmd('a', a, b);\n    }\n}",
        "题目要求删除命令先于新增命令，且各自按 id1 升序；按矩阵下标扫描天然有序。",
        ["按请求历史输出而不是按最终差集输出", "新增排在删除前", "没有保证 id1 < id2"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_idle_server_running_count",
        "服务器空闲-维护每台服务器运行计数",
        "同一服务器同一时刻可并行任务，用 running[server] 从 0 到 1 时更新工作服务器数。",
        "classic_server_idle",
        ["扫描线", "计数数组"],
        "void apply_delta(int sid, int delta, int running[], int *working) {\n    /* TODO */\n}",
        "void apply_delta(int sid, int delta, int running[], int *working) {\n    int before = running[sid];\n    running[sid] += delta;\n    if (before == 0 && running[sid] > 0) ++*working;\n    if (before > 0 && running[sid] == 0) --*working;\n}",
        "并行任务意味着不能用 bool；只有运行数跨过 0/1 边界时，工作服务器数才变化。",
        ["结束一个任务就认为服务器空闲", "没有处理同服务器重叠任务", "working 重复加减"],
        [],
    ),
    drill(
        "classic_idle_batch_same_time_events",
        "服务器空闲-同一时刻事件批处理",
        "扫描相邻时间点区间 [t,nextT)，先处理当前时刻所有 start/end 事件，再判断该区间状态。",
        "classic_server_idle",
        ["扫描线", "事件排序"],
        "/* events 已按 time 排序 */\nwhile (i < m) {\n    int t = events[i].time;\n    /* TODO */\n}",
        "while (i < m) {\n    int t = events[i].time;\n    while (i < m && events[i].time == t) {\n        apply_delta(events[i].sid, events[i].delta, running, &working);\n        ++i;\n    }\n    if (i < m && serverNum - working == 1 && t < events[i].time) {\n        add_interval(t, events[i].time);\n    }\n}",
        "时段状态只在事件点之间保持不变；同一时刻的所有变化必须合并后再看下一个区间。",
        ["边处理事件边立刻输出零长度区间", "同一时间 start/end 顺序影响结果", "忘记跳过 t==nextT"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_idle_merge_adjacent",
        "服务器空闲-合并相邻区间",
        "把 [1,2] 和 [2,3] 合并为 [1,3]。",
        "classic_server_idle",
        ["区间合并"],
        "void append_interval(int l, int r) {\n    /* TODO */\n}",
        "void append_interval(int l, int r) {\n    if (ansN > 0 && ans[ansN - 1].endTime == l) {\n        ans[ansN - 1].endTime = r;\n    } else {\n        ans[ansN++] = (Interval){l, r};\n    }\n}",
        "题目要求连续时段合并，追加新区间前只需要看上一个区间的右端点。",
        ["只合并重叠不合并相邻", "产生 [2,2] 零长度区间"],
        [],
    ),
    drill(
        "classic_tlv_hex_pair_to_byte",
        "TLV-十六进制两字符转字节",
        "把 hexStream 中两个十六进制字符转成 0..255 的字节值。",
        "classic_tlv_parse",
        ["字符串处理", "进制转换", "TLV"],
        "int hex_byte(const char *s) {\n    return 0;\n}",
        "int hex_val(char c) { return c <= '9' ? c - '0' : c - 'a' + 10; }\nint hex_byte(const char *s) {\n    return hex_val(s[0]) * 16 + hex_val(s[1]);\n}",
        "码流每两个字符表示一个字节；题目限定小写 a-f。",
        ["把两个字符当十进制解析", "忘记高 4 位乘 16", "没有处理 a-f"],
        ["strtol"],
        input_example='"6f"',
        expected_output="111",
    ),
    drill(
        "classic_tlv_read_big_endian_len",
        "TLV-读取大端 Length",
        "从 4 字节 Length 字段读取大端整数。",
        "classic_tlv_parse",
        ["位运算", "进制转换", "TLV"],
        "int read_len(const unsigned char *b) {\n    return 0;\n}",
        "int read_len(const unsigned char *b) {\n    return ((int)b[0] << 24) | ((int)b[1] << 16) | ((int)b[2] << 8) | b[3];\n}",
        "大端序是高字节在前，拼接时前面的字节左移更多。",
        ["按小端拼接", "char 有符号导致移位异常", "只读了 2 字节"],
        [],
    ),
    drill(
        "classic_tlv_tag_nested_bit",
        "TLV-判断 Tag 最高位是否嵌套",
        "T 域 2 字节，最高位为 1 表示 Value 中还有子 TLV。",
        "classic_tlv_parse",
        ["位运算", "TLV"],
        "int is_nested(unsigned short tag) {\n    return 0;\n}",
        "int is_nested(unsigned short tag) {\n    return (tag & 0x8000) != 0;\n}",
        "2 字节 Tag 的最高位掩码是 0x8000。",
        ["用 0x80 判断整个 2 字节 Tag", "把长度字段拿来判断嵌套"],
        [],
        input_example="tag=0x8001",
        expected_output="1",
    ),
    drill(
        "classic_tlv_recursive_limit",
        "TLV-递归解析子 TLV 到结束偏移",
        "嵌套 TLV 的 Value 区间是 [valueStart, valueStart+len)，递归只解析这段。",
        "classic_tlv_parse",
        ["递归", "DFS", "TLV"],
        "void parse_range(int pos, int end, int level) {\n    /* TODO */\n}",
        "void parse_range(int pos, int end, int level) {\n    while (pos < end) {\n        int tag = read_tag(pos);\n        int len = read_len_at(pos + 2);\n        int value = pos + 6;\n        if (tag & 0x8000) parse_range(value, value + len, level + 1);\n        else emit_leaf(level, value, len);\n        pos = value + len;\n    }\n}",
        "每个 TLV 长度是 2 字节 T + 4 字节 L + len 字节 V；递归必须受父节点 Value 结束位置限制。",
        ["递归直接解析到全局结尾", "pos 没跳过当前 Value", "叶子节点 level 写错"],
        [],
        difficulty=3,
        seconds=150,
    ),
    drill(
        "classic_dir_parse_level_name",
        "目录删除-解析层级和目录名",
        "从 `|-|-Cpp` 解析出 level=2, name=Cpp。",
        "classic_delete_dirs",
        ["字符串处理", "树"],
        "int parse_line(const char *line, char *name) {\n    return 0;\n}",
        "int parse_line(const char *line, char *name) {\n    int level = 0;\n    while (line[0] == '|' && line[1] == '-') {\n        ++level;\n        line += 2;\n    }\n    strcpy_s(name, 128, line);\n    return level;\n}",
        "`|-` 每出现一次表示下一层；剩余部分就是目录名。",
        ["按字符 `|` 个数但没有跳过 `-`", "目录名里残留层级符号", "根目录 level 处理成 1"],
        ["strcpy_s"],
    ),
    drill(
        "classic_dir_build_by_stack",
        "目录删除-用栈挂接父子关系",
        "按输入顺序读取目录行，level 为 k 的节点挂到 stack[k-1] 下。",
        "classic_delete_dirs",
        ["树", "栈"],
        "/* level/name 已解析 */\n/* TODO: 找父节点并更新 stack */",
        "Node *node = new_node(name);\nif (level > 0) add_child(stack[level - 1], node);\nstack[level] = node;",
        "输入保证每个子目录挂接在前面最近的上一层目录下，栈正好保存每层最近节点。",
        ["用前一个节点当父节点", "没有覆盖 stack[level]", "level=0 时访问 stack[-1]"],
        [],
    ),
    drill(
        "classic_dir_postorder_delete",
        "目录删除-后序删除可级联叶子",
        "子目录删除后父目录可能变成叶子，因此要后序遍历再判断当前节点。",
        "classic_delete_dirs",
        ["DFS", "树", "后序遍历"],
        "int dfs(Node *x) {\n    return 0;\n}",
        "int dfs(Node *x) {\n    int alive = 0;\n    for (int i = 0; i < x->childNum; ++i) {\n        alive += dfs(x->child[i]);\n    }\n    if (alive == 0 && in_del_set(x->name) && x->parent != NULL) {\n        ++deletedCount;\n        return 0;\n    }\n    return 1;\n}",
        "只有叶子目录能删；先处理子节点，当前节点才能知道自己是否因子节点删除而变成叶子。",
        ["先序判断导致不能级联删除", "把根目录也删除", "按名字去重而不是按不同路径计数"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_mac_validate_window",
        "MAC-校验 17 字符窗口",
        "判断长度 17 的子串是否形如 XX-XX-XX-XX-XX-XX 或 XX:XX:XX:XX:XX:XX。",
        "classic_mac_parse",
        ["字符串处理", "枚举"],
        "int is_mac_window(const char *s) {\n    return 0;\n}",
        "int is_hex(char c) { return isdigit((unsigned char)c) || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F'); }\nint is_mac_window(const char *s) {\n    char sep = s[2];\n    if (sep != '-' && sep != ':') return 0;\n    for (int i = 0; i < 17; ++i) {\n        if ((i + 1) % 3 == 0) { if (s[i] != sep) return 0; }\n        else if (!is_hex(s[i])) return 0;\n    }\n    return 1;\n}",
        "合法 MAC 固定 17 字符，分隔符位置固定且整串只能使用同一种分隔符。",
        ["允许 - 和 : 混用", "只检查了 12 个十六进制字符没检查分隔符位置", "把 g 当成合法 hex"],
        ["isdigit"],
        difficulty=3,
    ),
    drill(
        "classic_mac_normalize_key",
        "MAC-归一化用于去重",
        "把合法 MAC 归一化为 12 位小写十六进制，不保留分隔符。",
        "classic_mac_parse",
        ["字符串处理", "哈希"],
        "void normalize_mac(const char *s, char *key) {\n    /* TODO */\n}",
        "void normalize_mac(const char *s, char *key) {\n    int k = 0;\n    for (int i = 0; i < 17; ++i) {\n        if (s[i] == '-' || s[i] == ':') continue;\n        key[k++] = (char)tolower((unsigned char)s[i]);\n    }\n    key[k] = '\\0';\n}",
        "题目规定大小写和分隔符不同但十六进制内容相同的 MAC 视为同一个。",
        ["把分隔符也放进 key", "没有统一大小写", "key 没加结尾 0"],
        ["tolower"],
    ),
    drill(
        "classic_mac_scan_overlap",
        "MAC-滑动窗口允许重叠匹配",
        "在 `01-02-03-04-05-06-07` 中要找到两个重叠 MAC。",
        "classic_mac_parse",
        ["滑窗", "枚举", "去重"],
        "for (int i = 0; input[i + 16] != '\\0'; ++i) {\n    /* TODO */\n}",
        "for (int i = 0; input[i + 16] != '\\0'; ++i) {\n    if (is_mac_window(input + i)) {\n        char key[13];\n        normalize_mac(input + i, key);\n        add_to_set(key);\n    }\n}",
        "不能匹配到一个 MAC 后直接跳 17 位，因为合法 MAC 可能重叠出现。",
        ["匹配后跳过整个窗口", "没有去重", "窗口边界少扫最后一个位置"],
        [],
    ),
    drill(
        "classic_mutex_conflict_mask",
        "程序互斥-构建冲突 bitmask",
        "n <= 20，用 conflict[i] 的二进制位表示与程序 i 互斥的程序。",
        "classic_mutex_programs",
        ["位运算", "图"],
        "void add_mutex(int a, int b) {\n    /* TODO */\n}",
        "void add_mutex(int a, int b) {\n    --a; --b;\n    conflict[a] |= 1u << b;\n    conflict[b] |= 1u << a;\n}",
        "互斥关系是无向的；题目程序编号从 1 开始，数组下标从 0 开始。",
        ["只加单向边", "忘记编号减 1", "n=20 时用 short 溢出"],
        [],
    ),
    drill(
        "classic_mutex_check_independent",
        "程序互斥-判断集合是否和谐",
        "给定 mask，判断集合内任意两个程序是否都不互斥。",
        "classic_mutex_programs",
        ["位运算", "枚举"],
        "int is_ok(unsigned mask) {\n    return 1;\n}",
        "int is_ok(unsigned mask) {\n    for (int i = 0; i < n; ++i) {\n        if ((mask & (1u << i)) && (conflict[i] & mask)) return 0;\n    }\n    return 1;\n}",
        "若集合中存在 i，且 conflict[i] 与集合有交集，则该集合不是和谐程序组。",
        ["没有排除集合外冲突", "只检查相邻编号", "重复计算可以接受但不能漏查"],
        [],
    ),
    drill(
        "classic_mutex_best_tie",
        "程序互斥-数量优先，运行时间和次优",
        "枚举和谐集合时，先最大化程序数量，再最小化运行时间和。",
        "classic_mutex_programs",
        ["枚举", "位运算", "最优化"],
        "void update_best(unsigned mask, int sum) {\n    /* TODO */\n}",
        "void update_best(unsigned mask, int sum) {\n    int cnt = popcount(mask);\n    if (cnt > bestCnt || (cnt == bestCnt && sum < bestSum)) {\n        bestCnt = cnt;\n        bestSum = sum;\n    }\n}",
        "题目不是找运行时间最小的任意集合，而是在程序数量最多的集合中取运行时间和最小。",
        ["先按运行时间排序导致数量不足", "相同数量时取了更大的 sum", "没有初始化 bestSum 为大值"],
        [],
    ),
    drill(
        "classic_indent_positive_diffs",
        "代码缩进-最少操作等于正增量之和",
        "对 [1,2,3,2,1]，答案是 1+(2-1)+(3-2)=3。",
        "classic_code_indent",
        ["贪心", "数组"],
        "long long min_steps(const int *a, int n) {\n    return 0;\n}",
        "long long min_steps(const int *a, int n) {\n    long long ans = a[0];\n    for (int i = 1; i < n; ++i) {\n        if (a[i] > a[i - 1]) ans += a[i] - a[i - 1];\n    }\n    return ans;\n}",
        "一次操作可作用于连续多行，新增一层缩进只会在高度从低到高的位置开始。",
        ["把答案写成所有缩进之和", "下降时也加差值", "使用 int 可能溢出"],
        [],
    ),
    drill(
        "classic_indent_boundary_zero",
        "代码缩进-处理首行和 0 缩进",
        "首行需要 a[0] 次操作；后续只看比前一行增加的部分。",
        "classic_code_indent",
        ["边界条件", "贪心"],
        "int first_contrib(const int *a) {\n    return 0;\n}",
        "int first_contrib(const int *a) {\n    return a[0];\n}",
        "把数组左侧看作高度 0，首行从 0 增加到 a[0] 的部分也要计入。",
        ["忽略首行", "空数组没处理", "把 0 缩进行当成一次操作"],
        [],
        difficulty=1,
    ),
    drill(
        "classic_tree_build_compact_level",
        "均匀拆分-按紧凑层序构建左右孩子",
        "pool 中 -1 节点不是有效节点，且它的孩子不再给出；用队列给有效节点分配孩子。",
        "classic_even_tree_split",
        ["树", "队列"],
        "/* pool[0] 是根，idx 指向下一个输入 */\nwhile (head < tail && idx < n) {\n    /* TODO */\n}",
        "while (head < tail && idx < n) {\n    int u = q[head++];\n    if (idx < n && pool[idx] != -1) left[u] = idx, q[tail++] = idx;\n    ++idx;\n    if (idx < n && pool[idx] != -1) right[u] = idx, q[tail++] = idx;\n    ++idx;\n}",
        "题目不是普通堆式 2*i+1 下标；-1 的孩子不再出现，所以要按有效节点队列消费输入。",
        ["直接用 2*i+1/2*i+2", "把 -1 也入队", "输出新下标而不是原数组下标"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_tree_subtree_sum",
        "均匀拆分-DFS 计算子树和",
        "递归计算每个有效节点的子树和。",
        "classic_even_tree_split",
        ["DFS", "树", "递归"],
        "long long dfs_sum(int u) {\n    return 0;\n}",
        "long long dfs_sum(int u) {\n    if (u < 0) return 0;\n    long long s = pool[u];\n    s += dfs_sum(left[u]);\n    s += dfs_sum(right[u]);\n    subSum[u] = s;\n    return s;\n}",
        "拆分条件依赖每个子树的节点值总和，先做后序 DFS。",
        ["把 -1 当成节点值参与求和", "用 int 存 1e9*1e4 溢出", "先序时子树和未完整"],
        [],
    ),
    drill(
        "classic_tree_find_half",
        "均匀拆分-找非根节点半和",
        "总和为偶数时，查找 subSum[u] == total/2 的非根节点。",
        "classic_even_tree_split",
        ["树", "查找"],
        "int find_cut(int nodeCount, long long total) {\n    return -1;\n}",
        "int find_cut(int nodeCount, long long total) {\n    if (total % 2 != 0) return -1;\n    for (int i = 1; i < nodeCount; ++i) {\n        if (subSum[i] == total / 2) return i;\n    }\n    return -1;\n}",
        "切掉一条边后，两边相等等价于某个非根子树和为 total/2。",
        ["允许根节点作为答案", "总和奇数仍查找", "返回遍历编号而不是 pool 下标"],
        [],
    ),
    drill(
        "classic_grid_multisource_bfs_init",
        "最小距离和-多源 BFS 初始化",
        "把所有仓库 0 同时入队，距离设为 0。",
        "classic_min_distance_sum",
        ["BFS", "队列", "矩阵"],
        "void init_sources(int **matrix, int rows, int cols) {\n    /* TODO */\n}",
        "void init_sources(int **matrix, int rows, int cols) {\n    for (int r = 0; r < rows; ++r) {\n        for (int c = 0; c < cols; ++c) {\n            dist[r][c] = -1;\n            if (matrix[r][c] == 0) {\n                dist[r][c] = 0;\n                push(r, c);\n            }\n        }\n    }\n}",
        "每个零售店要到最近仓库的距离，多源 BFS 一次即可得到所有最近距离。",
        ["对每个零售店单独 BFS 超时", "忘记把所有仓库入队", "障碍也入队"],
        [],
    ),
    drill(
        "classic_grid_bfs_skip_obstacle",
        "最小距离和-BFS 跳过障碍和已访问",
        "扩展四邻接时，越界、障碍 -1、已访问都要跳过。",
        "classic_min_distance_sum",
        ["BFS", "矩阵", "边界条件"],
        "if (/* TODO */) continue;",
        "if (nr < 0 || nr >= rows || nc < 0 || nc >= cols) continue;\nif (matrix[nr][nc] == -1 || dist[nr][nc] != -1) continue;",
        "BFS 的访问条件必须同时保证合法位置、可通行、未访问。",
        ["把零售店 1 当障碍", "重复入队导致距离被覆盖", "行列边界写反"],
        [],
    ),
    drill(
        "classic_grid_sum_reachable_stores",
        "最小距离和-只统计可达零售店",
        "BFS 后只累加 matrix==1 且 dist!=-1 的格子。",
        "classic_min_distance_sum",
        ["BFS", "数组统计"],
        "int sum = 0;\n/* TODO */",
        "int sum = 0;\nfor (int r = 0; r < rows; ++r) {\n    for (int c = 0; c < cols; ++c) {\n        if (matrix[r][c] == 1 && dist[r][c] >= 0) sum += dist[r][c];\n    }\n}",
        "无法到达仓库的零售店不参与距离和；没有仓库时所有 dist 都是 -1，结果自然为 0。",
        ["把不可达距离 -1 加进 sum", "把仓库距离也加进去", "没有零售店时返回异常值"],
        [],
    ),
    drill(
        "classic_cache_next_pos",
        "数据库缓存-预处理下一次出现位置",
        "对每个访问位置 i，求同一 dataId 下一次出现的位置，没有则 INF。",
        "classic_db_cache",
        ["哈希", "数组", "预处理"],
        "for (int i = n - 1; i >= 0; --i) {\n    /* TODO */\n}",
        "for (int i = n - 1; i >= 0; --i) {\n    int id = dataIds[i];\n    nextPos[i] = last[id];\n    last[id] = i;\n}",
        "最少数据库访问次数是最优缓存替换，淘汰未来最晚再访问或不再访问的数据。",
        ["用 LRU 代替最优策略", "没有处理不再访问的 INF", "last 初始化不是 INF"],
        [],
    ),
    drill(
        "classic_cache_belady_evict",
        "数据库缓存-淘汰未来最晚访问的数据",
        "缓存满且 miss 时，删除 nextUse 最大的缓存项。",
        "classic_db_cache",
        ["贪心", "缓存", "优先队列"],
        "int choose_victim(void) {\n    return -1;\n}",
        "int choose_victim(void) {\n    int victim = -1, farthest = -1;\n    for (int k = 0; k < cacheN; ++k) {\n        if (cacheNext[k] > farthest) {\n            farthest = cacheNext[k];\n            victim = k;\n        }\n    }\n    return victim;\n}",
        "Belady 最优策略：淘汰未来最晚才会用到的数据，若不再使用则最应该淘汰。",
        ["淘汰最近使用的数据", "命中后没有更新 nextUse", "缓存未满也淘汰"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_cache_hit_update_next",
        "数据库缓存-命中后更新下一次访问位置",
        "访问命中缓存时，不增加数据库访问次数，但要更新该缓存项的 nextUse。",
        "classic_db_cache",
        ["缓存", "状态模拟"],
        "if (pos >= 0) {\n    /* TODO */\n}",
        "if (pos >= 0) {\n    cacheNext[pos] = nextPos[i];\n} else {\n    ++dbVisits;\n    insert_or_evict(dataIds[i], nextPos[i]);\n}",
        "命中不访问数据库；但下一次访问位置已经向后推进，缓存元数据必须同步。",
        ["命中也加访问次数", "nextUse 保持旧值导致后续淘汰错误"],
        [],
    ),
    drill(
        "classic_route_bfs_tie_weight",
        "最佳路径-BFS 中维护最少跳数下的最小权值",
        "从起点出发，先保证跳数最少；同一跳数到达同一节点时保留更小权值。",
        "classic_best_route",
        ["BFS", "图", "最短路"],
        "if (dist[v] == -1 || dist[v] == dist[u] + 1 && cost > newCost) {\n    /* TODO */\n}",
        "if (dist[v] == -1 || (dist[v] == dist[u] + 1 && cost[v] > newCost)) {\n    dist[v] = dist[u] + 1;\n    cost[v] = newCost;\n    push(v);\n}",
        "最佳路径先比连接个数，再比权值；不能直接用 Dijkstra 按权值最小。",
        ["只按权值最小选路径", "同跳数更小权值没有更新", "把有向边当无向边"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_route_build_directed_adj",
        "最佳路径-构建有向邻接表",
        "connections[i] 是 src -> snk 的单向边，不能反向加入。",
        "classic_best_route",
        ["图", "邻接表"],
        "void add_edge(int u, int v, int w) {\n    /* TODO */\n}",
        "void add_edge(int u, int v, int w) {\n    edges[edgeCnt] = (Edge){v, w, head[u]};\n    head[u] = edgeCnt++;\n}",
        "题目明确是有向连接；反向路径不存在时查询应返回 -1。",
        ["加入双向边", "没有初始化 head 为 -1", "节点编号上限 1000 数组开小"],
        [],
    ),
    drill(
        "classic_route_answer_unreachable",
        "最佳路径-不可达返回 -1",
        "查询结束后，如果目的节点 dist 仍为 -1，则该查询答案为 -1。",
        "classic_best_route",
        ["图", "边界条件"],
        "ans[i] = cost[to];",
        "ans[i] = (dist[to] == -1) ? -1 : cost[to];",
        "有 0 条或多条路径，没路径时不能输出默认 cost=0。",
        ["不可达输出 0", "上一轮查询的 dist 没清空", "from==to 特殊情况没定义清楚"],
        [],
    ),
    drill(
        "classic_topo_dependency_direction",
        "任务调度-依赖边方向",
        "relations[i]=[id1,id2] 表示 id1 依赖 id2，应建边 id2 -> id1。",
        "classic_task_schedule",
        ["拓扑排序", "图"],
        "void add_relation(int id1, int id2) {\n    /* TODO */\n}",
        "void add_relation(int id1, int id2) {\n    add_edge(id2, id1);\n    ++indeg[id1];\n}",
        "谁被依赖谁先执行，所以边从前置任务指向后置任务。",
        ["建成 id1->id2", "入度加在 id2 上", "任务编号 1..taskNum 下标混乱"],
        [],
    ),
    drill(
        "classic_topo_layer_minutes",
        "任务调度-按拓扑层计算分钟数",
        "每分钟可以并行执行所有当前入度为 0 的任务，层数就是最短时间。",
        "classic_task_schedule",
        ["拓扑排序", "BFS", "层序遍历"],
        "while (queue_not_empty()) {\n    int cnt = queue_size();\n    /* TODO */\n}",
        "while (queue_not_empty()) {\n    int cnt = queue_size();\n    ++minutes;\n    while (cnt--) {\n        int u = pop();\n        for (int e = head[u]; e != -1; e = edges[e].next) {\n            int v = edges[e].to;\n            if (--indeg[v] == 0) push(v);\n        }\n    }\n}",
        "任务耗时都为 1，并行资源充足；一层入度为 0 的任务一起执行。",
        ["逐个任务加时间", "新变 0 入度的任务在同一分钟执行", "没有处理无依赖任务"],
        [],
    ),
    drill(
        "classic_topo_zero_relations",
        "任务调度-无依赖时答案为 1",
        "如果 taskNum>0 且 relations 为空，所有任务可并行，最短时间是 1。",
        "classic_task_schedule",
        ["边界条件", "拓扑排序"],
        "if (relationsSize == 0) return 0;",
        "if (relationsSize == 0) return taskNum > 0 ? 1 : 0;",
        "只要有任务，且都无依赖，它们可以在第 1 分钟全部完成。",
        ["返回 taskNum", "返回 0", "只把出现在关系里的任务入队"],
        [],
        difficulty=1,
    ),
    drill(
        "classic_version_parse_to_int",
        "版本满足度-版本号转整数比较",
        "把 x.y.z 转成 x*1000000 + y*1000 + z，缺失段补 0。",
        "classic_version_range",
        ["字符串处理", "进制转换", "比较"],
        "int version_value(const char *s) {\n    return 0;\n}",
        "int version_value(const char *s) {\n    int x = 0, y = 0, z = 0;\n    sscanf_s(s, \"%d.%d.%d\", &x, &y, &z);\n    return x * 1000000 + y * 1000 + z;\n}",
        "每段范围 0..999，可用固定进制 1000 压成一个整数，方便比较。",
        ["缺失段没有补 0", "用字符串字典序比较版本", "乘数不是 1000 导致冲突"],
        ["sscanf_s"],
    ),
    drill(
        "classic_version_greater_next",
        "版本满足度-> 操作符左边界加 1",
        "`>1.1.999` 等价于 `>=1.2.0`，需要处理进位。",
        "classic_version_range",
        ["边界条件", "进位"],
        "int next_version(int v) {\n    return v + 1;\n}",
        "int next_version(int v) {\n    return v + 1;\n}",
        "压成整数后相邻版本直接 +1；999 进位自然体现在整数编码里。",
        ["把 > 当成 >= 处理", "z=999 时没有进位", "超过最大版本没截断"],
        [],
        input_example=">1.1.999",
        expected_output="lower=1.2.0",
    ),
    drill(
        "classic_version_tilde_bounds",
        "版本满足度-计算 ~ 范围",
        "根据给定段数，`~1` 到下一个主版本，`~1.9` 到下一个次版本。",
        "classic_version_range",
        ["字符串处理", "区间", "边界条件"],
        "void parse_tilde(int x, int y, int z, int parts, int *l, int *r) {\n    /* TODO */\n}",
        "void parse_tilde(int x, int y, int z, int parts, int *l, int *r) {\n    *l = x * 1000000 + y * 1000 + z;\n    if (parts == 1) *r = (x + 1) * 1000000 - 1;\n    else *r = x * 1000000 + (y + 1) * 1000 - 1;\n}",
        "~ 的右边界取决于是否给了次版本；这是本题最容易出错的分支。",
        ["把 ~1 和 ~1.0 当成一样", "右边界写成开区间但后续按闭区间比较", "缺失 z 没补 0"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_version_intersection",
        "版本满足度-闭区间求交",
        "两个版本范围转成闭区间 [l,r] 后，判断是否有交集。",
        "classic_version_range",
        ["区间", "比较"],
        "int has_intersection(int l1, int r1, int l2, int r2) {\n    return 0;\n}",
        "int has_intersection(int l1, int r1, int l2, int r2) {\n    return l1 <= r2 && l2 <= r1;\n}",
        "闭区间相交条件是双方左端点都不超过对方右端点。",
        ["只判断 l1<=r2", "把相等边界当成不相交", "没有先统一成闭区间"],
        [],
    ),
    drill(
        "classic_deliver_can_limit",
        "蔬菜配送-判断给定时限是否可行",
        "给定 limit，贪心把连续社区分给尽量少的志愿者，判断人数是否 <= num。",
        "classic_community_delivery",
        ["贪心", "二分答案"],
        "int can_finish(int num, const int *a, int n, int limit) {\n    return 0;\n}",
        "int can_finish(int num, const int *a, int n, int limit) {\n    int used = 1, sum = 0;\n    for (int i = 0; i < n; ++i) {\n        if (a[i] > limit) return 0;\n        if (sum + a[i] > limit) { ++used; sum = 0; }\n        sum += a[i];\n    }\n    return used <= num;\n}",
        "每个志愿者负责连续社区，给定最大耗时后用顺序贪心切段即可。",
        ["没有处理单个社区超过 limit", "切段后忘记把当前社区加入新段", "社区不能重排"],
        [],
    ),
    drill(
        "classic_deliver_binary_search",
        "蔬菜配送-二分最小最大段和",
        "答案在 max(communities) 到 sum(communities) 之间二分。",
        "classic_community_delivery",
        ["二分答案", "贪心"],
        "while (l < r) {\n    int mid = (l + r) / 2;\n    /* TODO */\n}",
        "while (l < r) {\n    int mid = l + (r - l) / 2;\n    if (can_finish(num, communities, n, mid)) r = mid;\n    else l = mid + 1;\n}",
        "可行性关于 limit 单调：limit 越大越容易完成，因此可以二分最小可行值。",
        ["左边界设 0 导致多余搜索", "可行时移动 l", "mid 溢出"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_deliver_more_workers_than_communities",
        "蔬菜配送-志愿者多于社区的边界",
        "如果志愿者数量不少于社区数，答案就是单个社区最大家庭数。",
        "classic_community_delivery",
        ["边界条件", "二分答案"],
        "if (num >= n) return 0;",
        "if (num >= n) return max_value(communities, n);",
        "每个社区只能由一个志愿者配送，志愿者再多也不能把一个社区拆开。",
        ["返回总和", "返回 0", "错误地把一个社区拆给多个人"],
        [],
        difficulty=1,
    ),
    drill(
        "classic_scaling_deadline_batches",
        "弹性伸缩-为每批消息记录截止时间",
        "每批 time,msgNum 的消息必须在 time+5 前处理完。",
        "classic_scaling_system",
        ["队列", "状态模拟"],
        "void add_batch(int time, int msgNum) {\n    /* TODO */\n}",
        "void add_batch(int time, int msgNum) {\n    if (msgNum > 0) {\n        batches[tail++] = (Batch){time + 5, msgNum};\n    }\n}",
        "消费时长固定 1 秒，题目要求总时长 <=5，因此每批消息有固定 deadline。",
        ["deadline 写成 time+4", "msgNum=0 也入队", "没有按生产时间顺序保存"],
        [],
    ),
    drill(
        "classic_scaling_drain_elapsed",
        "弹性伸缩-两次决策间消费旧消息",
        "从 lastTime 到 time 之间，按当前机器数和 capability 消费队首批次。",
        "classic_scaling_system",
        ["队列", "模拟"],
        "void consume_elapsed(int seconds) {\n    /* TODO */\n}",
        "void consume_elapsed(int seconds) {\n    long long cap = 1LL * seconds * machineNum * capability;\n    while (cap > 0 && head < tail) {\n        int take = batches[head].left < cap ? batches[head].left : (int)cap;\n        batches[head].left -= take;\n        cap -= take;\n        if (batches[head].left == 0) ++head;\n    }\n}",
        "每次 judgeWithMsgs 只在决策时刻调整，中间按旧机器数持续消费。",
        ["先扩容再消费过去时间", "没有从队首 FIFO 消费", "int 乘法溢出"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_scaling_min_machine_by_deadline",
        "弹性伸缩-按 deadline 计算最少机器数",
        "假设未来不再扩缩容，求满足所有未完成批次 deadline 的最少机器数。",
        "classic_scaling_system",
        ["贪心", "二分/枚举", "队列"],
        "int need_machines(int now) {\n    return 1;\n}",
        "int need_machines(int now) {\n    long long prefix = 0;\n    int need = 1;\n    for (int i = head; i < tail; ++i) {\n        prefix += batches[i].left;\n        int seconds = batches[i].deadline - now;\n        int cur = (int)((prefix + 1LL * seconds * capability - 1) / (1LL * seconds * capability));\n        if (cur > need) need = cur;\n    }\n    return need;\n}",
        "按 deadline 升序看前缀工作量，任一 deadline 前必须处理完此前所有消息。",
        ["只看总消息量不看最早 deadline", "seconds 为 0 没处理", "缩容后允许机器数为 0"],
        [],
        difficulty=4,
        seconds=180,
    ),
    drill(
        "classic_fs_node_children",
        "文件系统-目录节点同时管理目录和文件名",
        "当前目录下目录名和文件名不能重复，创建前要在两类集合中都查。",
        "classic_file_system",
        ["数据结构设计", "哈希/Map"],
        "int exists(Node *dir, const char *name) {\n    return 0;\n}",
        "int exists(Node *dir, const char *name) {\n    return find_dir(dir, name) != NULL || find_file(dir, name) != NULL;\n}",
        "makeDir/createFile 的重名检查范围是当前目录下所有目录和文件。",
        ["只检查同类型重名", "检查了全局重名", "大小写敏感处理错误"],
        [],
    ),
    drill(
        "classic_fs_split_path",
        "文件系统-按 / 切分路径并忽略末尾空段",
        "把 `/a/b/` 或 `a/b/` 切成 a,b。",
        "classic_file_system",
        ["字符串处理", "路径解析"],
        "char *tok = strtok_s(buf, \"/\", &ctx);\nwhile (tok != NULL) {\n    /* TODO */\n}",
        "char *tok = strtok_s(buf, \"/\", &ctx);\nwhile (tok != NULL) {\n    visit_component(tok);\n    tok = strtok_s(NULL, \"/\", &ctx);\n}",
        "strtok_s 会跳过连续分隔符和末尾分隔符，适合本题合法路径。",
        ["把末尾空字符串当目录名", "没有复制 pathName 就直接 strtok 修改常量", "绝对路径没有从根开始"],
        ["strtok_s"],
    ),
    drill(
        "classic_fs_change_dir_start",
        "文件系统-changeDir 区分绝对/相对路径",
        "pathName 以 / 开头时从根目录开始，否则从当前目录开始。",
        "classic_file_system",
        ["路径解析", "树"],
        "Node *p = sys->cwd;\n/* TODO */",
        "Node *p = (pathName[0] == '/') ? sys->root : sys->cwd;",
        "绝对路径和相对路径的唯一区别是起点不同。",
        ["所有路径都从 cwd 开始", "空字符串错误切到 root", "末尾 / 当作失败"],
        [],
    ),
    drill(
        "classic_fs_list_dirs_then_files",
        "文件系统-listDir 目录在前文件在后",
        "返回当前目录下名称：目录升序在前，文件升序在后。",
        "classic_file_system",
        ["排序", "字符串处理"],
        "/* dirs/files 各自已有 */\n/* TODO: 排序并拼接 */",
        "qsort(dirs, dirN, sizeof(char *), cmp_str_ptr);\nqsort(files, fileN, sizeof(char *), cmp_str_ptr);\nfor (int i = 0; i < dirN; ++i) out[k++] = md_strdup(dirs[i]);\nfor (int i = 0; i < fileN; ++i) out[k++] = md_strdup(files[i]);",
        "题目要求目录和文件分别排序，不是把两类名称混在一起排序。",
        ["文件排到目录前", "整体排序导致 file 插入目录中间", "返回了内部字符串指针"],
        ["qsort", "strcmp"],
    ),
    drill(
        "classic_fs_remove_subtree",
        "文件系统-remove 删除目录整棵子树",
        "删除当前目录下的目录时，要释放它的所有子目录和文件。",
        "classic_file_system",
        ["树", "DFS", "资源释放"],
        "void free_node(Node *x) {\n    /* TODO */\n}",
        "void free_node(Node *x) {\n    for (int i = 0; i < x->dirN; ++i) free_node(x->dirs[i]);\n    for (int i = 0; i < x->fileN; ++i) free(x->files[i]);\n    free(x->name);\n    free(x);\n}",
        "remove 删除目录不是只从父节点摘掉指针，还要递归释放子树资源。",
        ["只删目录本身导致泄漏", "删除不存在名称返回 true", "删除 cwd 祖先后 cwd 悬挂"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_wb_split_write",
        "WriteBuffer-写请求按 8 字节拆分",
        "把 offset,len,value 拆成多个最多 8 字节的写请求，按地址递增入队。",
        "classic_write_buffer",
        ["队列", "模拟"],
        "while (len > 0) {\n    /* TODO */\n}",
        "while (len > 0) {\n    int chunk = len > 8 ? 8 : len;\n    push_req((WriteReq){offset, chunk, value});\n    offset += chunk;\n    len -= chunk;\n}",
        "每个缓存请求最多 8 字节，最后一段可以小于 8。",
        ["按 bufferCap*8 拆", "最后不足 8 字节丢失", "入队顺序不是地址从小到大"],
        [],
    ),
    drill(
        "classic_wb_flush_one_fifo",
        "WriteBuffer-FIFO 刷新最早写请求",
        "缓存满时，先把队首写请求写入主存，再放入新请求。",
        "classic_write_buffer",
        ["队列", "模拟"],
        "void flush_one(void) {\n    /* TODO */\n}",
        "void flush_one(void) {\n    WriteReq r = q[head++];\n    for (int i = 0; i < r.len; ++i) data[r.offset + i] = (uint8_t)r.value;\n}",
        "FIFO 只能从队首取出，不能挑任意请求。",
        ["从队尾刷新", "只移动 head 没写主存", "写入长度越界"],
        [],
    ),
    drill(
        "classic_wb_read_overlap_flush_prefix",
        "WriteBuffer-读命中缓存时刷新前缀",
        "读范围与第 k 个缓存写请求相交时，必须刷新 0..k 的所有请求。",
        "classic_write_buffer",
        ["队列", "区间相交"],
        "int overlap(WriteReq r, int off, int len) {\n    return 0;\n}",
        "int overlap(WriteReq r, int off, int len) {\n    int a1 = r.offset, a2 = r.offset + r.len;\n    int b1 = off, b2 = off + len;\n    return a1 < b2 && b1 < a2;\n}",
        "读范围是半开区间 [off,off+len)，写请求也是半开区间；相交后按 FIFO 刷到该请求为止。",
        ["只刷新相交请求不刷新之前请求", "闭区间判断导致边界相邻误判", "读操作直接读缓存不刷主存"],
        [],
        difficulty=3,
    ),
    drill(
        "classic_wb_sync_all",
        "WriteBuffer-同步操作刷新全部缓存",
        "op=3 时把缓存中所有写请求按 FIFO 写回主存。",
        "classic_write_buffer",
        ["队列", "模拟"],
        "void sync_all(void) {\n    /* TODO */\n}",
        "void sync_all(void) {\n    while (head < tail) {\n        flush_one();\n    }\n}",
        "同步操作结束后缓存为空，主存包含全部已提交写。",
        ["只刷新一个请求", "刷新后没有清空队列", "同步时顺序不是 FIFO"],
        [],
    ),
    drill(
        "classic_committer_file_masks",
        "Committer-把每个文件转成评审人 bitmask",
        "files[i] 中的 committer 编号范围 0..9，可用 10 位 mask 表示。",
        "classic_least_committers",
        ["位运算", "集合覆盖"],
        "int file_mask(int *arr, int n) {\n    return 0;\n}",
        "int file_mask(int *arr, int n) {\n    int mask = 0;\n    for (int i = 0; i < n; ++i) mask |= 1 << arr[i];\n    return mask;\n}",
        "每个文件允许多个 committer，bitmask 能快速判断某个选择集合是否覆盖该文件。",
        ["编号从 1 开始处理", "用加法导致重复编号出错", "mask 位数不够"],
        [],
    ),
    drill(
        "classic_committer_cover_check",
        "Committer-判断选择集合是否覆盖所有文件",
        "给定选择的 committer 集合 choose，检查每个文件是否至少有一位相交。",
        "classic_least_committers",
        ["位运算", "集合覆盖"],
        "int cover_all(int choose) {\n    return 1;\n}",
        "int cover_all(int choose) {\n    for (int i = 0; i < filesSize; ++i) {\n        if ((choose & fileMask[i]) == 0) return 0;\n    }\n    return 1;\n}",
        "每个文件至少需要一名可评审的 committer，不要求每个 committer 都被使用。",
        ["用 == fileMask 判断要求全员覆盖", "只检查第一个文件", "空交集仍认为可覆盖"],
        [],
    ),
    drill(
        "classic_committer_enum_min_popcount",
        "Committer-枚举最少评审人数",
        "枚举 0..(1<<10)-1 的 committer 集合，找覆盖所有文件且 popcount 最小的集合。",
        "classic_least_committers",
        ["位运算", "枚举", "集合覆盖"],
        "int ans = 11;\nfor (int s = 0; s < (1 << 10); ++s) {\n    /* TODO */\n}",
        "int ans = 11;\nfor (int s = 0; s < (1 << 10); ++s) {\n    if (cover_all(s)) {\n        int c = popcount(s);\n        if (c < ans) ans = c;\n    }\n}",
        "文件数最多 12，committer 编号只有 0..9，枚举 1024 个集合足够快。",
        ["按文件回溯但没有剪枝导致复杂", "枚举文件集合而不是 committer 集合", "没有初始化 ans 大于最大可能值"],
        [],
        difficulty=2,
    ),
]


def main():
    questions = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    by_id = {q["id"]: q for q in questions}
    added = 0
    for item in DRILLS:
        if item["id"] in by_id:
            by_id[item["id"]].update(item)
        else:
            questions.append(item)
            by_id[item["id"]] = item
            added += 1

    DATA_PATH.write_text(json.dumps(questions, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    PORTABLE_DATA_PATH.write_text(
        "window.QUESTIONS = " + json.dumps(questions, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    grouped = defaultdict(list)
    for item in DRILLS:
        grouped[item["source_problem"]].append(item)

    lines = [
        "# timu.txt 长题微题拆解",
        "",
        f"本次从 `timu.txt` 拆出 {len(DRILLS)} 道微题，覆盖 {len(grouped)} 个长题来源。",
        "",
        "| 长题来源 | 微题数量 | 微题 |",
        "| --- | ---: | --- |",
    ]
    for source in sorted(grouped):
        ids = ", ".join(item["id"] for item in grouped[source])
        lines.append(f"| `{source}` | {len(grouped[source])} | {ids} |")
    lines.extend(
        [
            "",
            "## 拆题原则",
            "",
            "- 每道微题只保留一个明确考点，例如解析、状态更新、区间合并、BFS 初始化、二分可行性判断。",
            "- 长业务背景不进入微题题干，题干只给最小输入和期望行为。",
            "- 对容易写错的边界保留在 `common_mistakes` 中，例如 `Search 前必须 Sort`、`有向边不能反加`、`最短路径先比跳数再比权重`。",
        ]
    )
    DOC_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"added_or_updated={len(DRILLS)} added={added} total={len(questions)}")


if __name__ == "__main__":
    main()
